---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/DPP4 Membrane/DPP4 Membrane.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/74776/articles/320467/master/file/figures/DPP4%20Membrane/DPP4%20Membrane.png"
    folder_url: "/users/74776/articles/320467/master/folder/figures/DPP4 Membrane"
