---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/gutjnl-2011-October-60-10-1412-F1-large/gutjnl-2011-October-60-10-1412-F1-large.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/74776/articles/320467/master/file/figures/gutjnl-2011-October-60-10-1412-F1-large/gutjnl-2011-October-60-10-1412-F1-large.png"
